#!/usr/bin/env python3
"""Put our closed-world cells next to the thesis's open-world cells.

These are NOT the same measurement, and the point of this table is to show
exactly where that matters. Their F1 is derived from pi_10 (r-precision at
r = 10, a 9.1% base rate) and recall at a per-model tuned threshold, against
the DUA-gated non-monitored background set. Ours is macro F1 over the monitored
classes with no background set at all.

The interesting result is that the two disagree wildly on one axis and barely
at all on the other, which is itself evidence about what the open world was
doing to each number.

Usage: python compare_to_paper.py
"""
import glob, json, os
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")

# Thesis Table 4.1 (cross-network, train AU / test CA) and Table 4.3 (drift),
# transcribed in logs/paper-numbers.md and confirmed against the PDF.
PAPER = {
    "k-FP":    dict(cn=0.430, m0=0.926, m2=0.761, m6=0.547),
    "DF":      dict(cn=0.939, m0=0.967, m2=0.854, m6=0.685),
    "Tik-Tok": dict(cn=0.872, m0=0.956, m2=0.827, m6=0.653),
    "RF":      dict(cn=0.046, m0=0.972, m2=0.907, m6=0.754),
    "Holmes":  dict(cn=0.009, m0=0.966, m2=0.740, m6=0.622),
}
ORDER = ["k-FP", "DF", "Tik-Tok", "RF", "Holmes"]


def stats(rows, axis, cell):
    v = [r["f1_macro"] for r in rows if r["axis"] == axis and r["cell"] == cell]
    return (float(np.mean(v)), float(np.std(v))) if v else None


def main():
    ours = {}
    for path in sorted(glob.glob(os.path.join(RESULTS, "*.json"))):
        if os.path.basename(path).startswith("rf-n"):
            continue
        d = json.load(open(path))
        if "rows" not in d:
            continue
        r = d["rows"]
        ours[d["classifier"]] = {
            "cn": stats(r, "cross-network", "ca"),
            "m0": stats(r, "drift", "in-dist"),
            "m2": stats(r, "drift", "month2"),
            "m6": stats(r, "drift", "month6"),
        }

    L = ["# Ours (closed world) against the thesis (open world)", "",
         "Generated by `src/compare_to_paper.py`. **These are different",
         "measurements.** Theirs is F1 from pi_10 and recall at a tuned threshold",
         "against the DUA-gated background set; ours is macro F1 over monitored",
         "classes with no background set. Differences below are therefore not",
         "errors, and agreement is not reproduction.", "",
         "| Classifier | Cross-network AU->CA | | | Drift month 2 | | | Drift month 6 | | |",
         "|---|---|---|---|---|---|---|---|---|---|",
         "| | theirs | ours | diff | theirs | ours | diff | theirs | ours | diff |"]

    def cells(name, key):
        p = PAPER[name][key]
        o = ours.get(name, {}).get(key)
        if o is None:
            return f" {p:.3f} | not run | n/a |"
        return f" {p:.3f} | {o[0]:.3f} | {o[0]-p:+.3f} |"

    for name in ORDER:
        if name not in ours:
            L.append(f"| {name} |" + "".join(f" {PAPER[name][k]:.3f} | not run | n/a |"
                                             for k in ("cn", "m2", "m6")))
            continue
        L.append(f"| {name} |" + "".join(cells(name, k) for k in ("cn", "m2", "m6")))

    # how big is the disagreement on each axis
    def mad(key):
        d = [abs(ours[n][key][0] - PAPER[n][key]) for n in ORDER
             if n in ours and ours[n][key]]
        return np.mean(d) if d else float("nan")

    L += ["",
          f"Mean absolute difference from the published number:",
          "",
          f"- cross-network: **{mad('cn'):.3f}**",
          f"- drift month 2: **{mad('m2'):.3f}**",
          f"- drift month 6: **{mad('m6'):.3f}**",
          "",
          "The drift column lands close to the published values and the",
          "cross-network column does not. That is the pattern you would predict if",
          "the open-world penalty is dominated by false positives against",
          "background traffic: a drift comparison moves both sides together and",
          "survives the background set being removed, while the cross-network cell",
          "was measuring precisely the failure that closed-world scoring deletes.",
          "",
          "It also means brief step 3, 'reproduce one paper number', stays",
          "**unsatisfiable** in the strict sense on open data: nothing here is the",
          "same measurement as anything in their tables. The drift agreement is",
          "corroboration, not reproduction, and should not be quoted as the latter."]

    out = os.path.join(RESULTS, "vs-paper.md")
    open(out, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
