#!/usr/bin/env python3
"""Recover, for each committed Holmes run, which classes could not be attributed.

run_holmes.py deviates from the authors' code, which asserts at least 12
validation samples per class: classes that cannot supply N_BG background plus
one attributed sample are skipped and take the median effective range, and
classes below N_ATTR are attributed over fewer samples (logs/deltas.md).

Runs made after that change record the lists in each result row as
`attr_coverage`. The runs already committed predate it and only printed them to
stdout, which was not kept. They are recoverable anyway: the split depends on
the label vector and the seed alone, so this script replays it from the labels
and writes logs/holmes-attr-coverage.md.

Needs the .npz files present (make data). Loads labels only, no GPU.

Usage: python holmes_coverage.py
"""
import glob, json, os
import numpy as np
from sklearn.model_selection import train_test_split

import data

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")

HOLDOUT, VALID_FRAC = 0.2, 0.15     # must match run_holmes.py
N_BG, N_ATTR = 2, 10


def labels_for(axis):
    """The training label vector of `axis`, in the classifier's 0..k-1 space."""
    spec = data.AXES[axis]
    ys = [np.load(os.path.join(data.DATA, spec["train"]))["y"].astype(np.int16)]
    ys += [np.load(os.path.join(data.DATA, v))["y"].astype(np.int16)
           for v in spec["test"].values()]
    keep = data.common_labels(*ys)
    return data.relabel(ys[0][np.isin(ys[0], keep)], keep), len(keep)


def coverage(ytr, n_classes, seed):
    ia, _ = train_test_split(np.arange(len(ytr)), test_size=HOLDOUT,
                             stratify=ytr, random_state=seed)
    _, ival = train_test_split(ia, test_size=VALID_FRAC,
                               stratify=ytr[ia], random_state=seed)
    yv = ytr[ival]
    skipped, short = [], []
    for c in range(n_classes):
        n = int((yv == c).sum())
        if n < N_BG + 1:
            skipped.append((c, n))
        elif n - N_BG < N_ATTR:
            short.append((c, n - N_BG))
    return skipped, short


def main():
    runs = sorted(glob.glob(os.path.join(RESULTS, "**", "holmes.json"),
                            recursive=True))
    if not runs:
        print("no holmes.json under results/")
        return 1

    L = ["# Holmes attribution coverage, per committed run", "",
         "Generated by `src/holmes_coverage.py`, replayed from the label vectors.",
         "",
         "*Skipped* = fewer than `N_BG + 1` = 3 validation samples, so the class",
         f"cannot be attributed at all and takes the median effective range.",
         f"*Short* = attributable but over fewer than `N_ATTR` = {N_ATTR} samples.",
         "Both are deviations from the authors' `assert >= 12`; see `deltas.md`.",
         ""]
    for path in runs:
        j = json.load(open(path))
        rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
        seeds = sorted({r["seed"] for r in j["rows"]})
        L += [f"## `{rel}`", ""]
        for axis in sorted({r["axis"] for r in j["rows"]}):
            ytr, k = labels_for(axis)
            L += [f"**{axis}** ({k} classes)", "",
                  "| seed | skipped (class: valid n) | short (class: attributed n) |",
                  "|---|---|---|"]
            for s in seeds:
                sk, sh = coverage(ytr, k, s)
                f = lambda v: ", ".join(f"{c}: {n}" for c, n in v) if v else "none"
                L.append(f"| {s} | {f(sk)} | {f(sh)} |")
            L.append("")

    out = os.path.join(ROOT, "logs", "holmes-attr-coverage.md")
    open(out, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
