#!/usr/bin/env python3
"""Write results/rf-slot-sweep.md from the RF slot-size sweep JSONs.

Appendix C.1 explains RF's cross-network collapse mechanically: the TAM slot
Tmax/(N-1) is far shorter than the roughly 150 ms RTT difference between the AU
training client and the CA test client, so widening the slot past that delta
should recover accuracy. This reproduces that sweep, and also runs it on the
drift axis, which the thesis does not do. The drift arm is the control: if
coarsening slots hurt only the cross-network cell, slot size would be
specifically a network-mismatch knob; if it hurts both, it is just information
loss.

Usage: python sweep_summary.py
"""
import json, os
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")

RUNS = [
    ("rf",             "cross-network", "1800 **(main)**"),
    ("rf-n300",        "cross-network", "300"),
    ("rf-n150",        "cross-network", "150"),
    ("rf",             "drift",         "1800 **(main)**"),
    ("rf-n300-drift",  "drift",         "300"),
    ("rf-n150-drift",  "drift",         "150"),
]


def load(tag):
    return json.load(open(os.path.join(RESULTS, f"{tag}.json")))


def cell(d, axis, name):
    v = [r["f1_macro"] for r in d["rows"] if r["axis"] == axis and r["cell"] == name]
    return (float(np.mean(v)), float(np.std(v))) if v else None


def main():
    L = ["# RF slot-size sensitivity, both axes", "",
         "Generated by `src/sweep_summary.py`. Reproduces the sweep the authors",
         "document in thesis Appendix C.1, and adds a drift arm they do not report.",
         "",
         "Tmax is 45.0 s for every collection here (measured, not assumed), and the",
         "slot is Tmax/(N-1) following their released code. The main table uses",
         "N = 1800; the other rows are sensitivity runs and are **not** folded into it.",
         ""]

    rows = {}
    for tag, axis, label in RUNS:
        d = load(tag)
        far = "ca" if axis == "cross-network" else "month6"
        rows[(tag, axis)] = (label, cell(d, axis, "in-dist"), cell(d, axis, far),
                             d["tam"]["slot_ms"] if tag == "rf" else load(tag)["tam"]["slot_ms"])

    for axis, far_label in (("cross-network", "cross-network CA"),
                            ("drift", "drift month 6")):
        L += [f"## {axis}", "",
              f"| N | Slot | in-dist | {far_label} | drop |", "|---|---|---|---|---|"]
        for tag, ax, _ in RUNS:
            if ax != axis:
                continue
            label, ind, far, slot = rows[(tag, ax)]
            L.append(f"| {label} | {slot} ms | {ind[0]:.4f} +/- {ind[1]:.4f} | "
                     f"{far[0]:.4f} +/- {far[1]:.4f} | {far[0]-ind[0]:+.3f} |")
        L.append("")

    L += ["## Result: the authors' remedy does not reproduce closed-world", "",
          "Widening the slot past the latency delta makes RF **worse**, monotonically,",
          "and on **both** axes. The thesis reports the opposite direction for the",
          "cross-network cell: recall about 0.01 at the default slot, rising to about",
          "0.18 at 150 ms and about 0.19 at 300 ms.",
          "",
          "These are not the same measurement, and the difference is informative rather",
          "than contradictory. Their sweep is open-world recall at a tuned threshold,",
          "starting from near-total collapse; the failure it repairs is false positives",
          "against the background set, which closed-world scoring removes by",
          "construction. Ours starts from 0.718, where there is no such failure left to",
          "repair, and coarser slots simply destroy information: even the",
          "in-distribution anchor falls on both axes.",
          "",
          "The drift arm is what makes this conclusive. If slot size were specifically",
          "a network-mismatch knob, coarsening it would damage the cross-network cell",
          "and leave drift alone. It damages both by a similar margin, so slot size is",
          "a general information-loss parameter, not the mechanism that separates the",
          "two axes.",
          "",
          "**Consequence for the verdict.** The obvious counter-reading of the two-axis",
          "claim, that RF's cross-network position is an artefact of one preprocessing",
          "constant and evaporates once that constant is set sensibly, is **not",
          "supported here**. RF's network-mismatch weakness survives the authors' own",
          "proposed fix, is worst at the setting that fix recommends, and its drift",
          "advantage is likewise not a slot-size artefact: RF is best on drift at the",
          "same fine 25 ms setting where it is worst across networks.",
          "",
          "Reproduce with:", "",
          "```",
          "python src/run_torch.py rf --seeds 3 --axes cross-network --slots 300 --tag rf-n300",
          "python src/run_torch.py rf --seeds 3 --axes cross-network --slots 150 --tag rf-n150",
          "python src/run_torch.py rf --seeds 3 --axes drift --slots 300 --tag rf-n300-drift",
          "python src/run_torch.py rf --seeds 3 --axes drift --slots 150 --tag rf-n150-drift",
          "python src/sweep_summary.py",
          "```"]

    out = os.path.join(RESULTS, "rf-slot-sweep.md")
    open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("\n".join(L[:34]))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
