#!/usr/bin/env python3
"""Write results/vantage/summary.md: both axes from one vantage, run twice.

The thesis's two headline axes do not share a training collection. Table 4.1
trains on AU and tests across networks; Table 4.3 trains on UK and tests across
time. Since AU-trained models degrade more in general (see
results/netpairs/summary.md), vantage and axis are entangled in the main result.

Each vantage axis removes that confound: one training collection, one 20%
in-distribution anchor, one label space, with both network cells and the drift
cell scored against it. Running it from two vantages then asks whether the
answer the confound-free test gives is itself vantage-dependent. It is, which is
why this script reads both.

Both vantages carry *two* network cells, and an earlier version of this script
scored both against ->CA only. That is the hardest target for every classifier
(netpairs/summary.md), so it silently picked the network-pessimistic cell of the
two and reported the result as if it were the vantage's answer. Every network
cell present is now read and reported, and the finding is computed per cell.

Usage: python vantage_summary.py
"""
import glob, json, os
from itertools import combinations
import numpy as np
from scipy.stats import spearmanr

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")
DRIFT_CELL = "month6"
ANCHOR = "in-dist"
# label, results dir, axis this vantage was run under, drift-cell caption
VANTAGES = [("AU", os.path.join(RESULTS, "vantage"), "vantage-au", "AU month 6"),
            ("UK", os.path.join(RESULTS, "vantage-uk"), "vantage-uk", "UK month 6")]
ORDER = ["k-FP", "DF", "Tik-Tok", "RF", "Holmes"]

_NTH = ("first", "second", "third", "fourth", "fifth", "sixth", "seventh",
        "eighth", "ninth", "tenth")


def ordinal_pos(i):
    return _NTH[i - 1] if i <= len(_NTH) else f"{i}th"


def commas(items):
    xs = list(items)
    return " and ".join(xs) if len(xs) < 3 else ", ".join(xs[:-1]) + " and " + xs[-1]


def load(d, axis):
    """One classifier per file, keyed by classifier name.

    Rows are filtered by axis as well as by cell. A results file may legitimately
    hold more than one axis (`run_torch.py df --axes vantage-au drift --tag
    vantage/df` is a natural invocation), and those axes have different training
    collections and label spaces, so averaging their like-named cells together
    would silently mix two populations.
    """
    out = {}
    for path in sorted(glob.glob(os.path.join(d, "*.json"))):
        j = json.load(open(path))
        r = [x for x in j["rows"] if x["axis"] == axis]
        if not r:
            continue
        cells = sorted({x["cell"] for x in r})
        m = lambda c: float(np.mean([x["f1_macro"] for x in r if x["cell"] == c]))
        sd = lambda c: float(np.std([x["f1_macro"] for x in r if x["cell"] == c]))
        if ANCHOR not in cells or DRIFT_CELL not in cells:
            continue
        a, drift = m(ANCHOR), m(DRIFT_CELL)
        nets = {}
        for c in cells:
            if c in (ANCHOR, DRIFT_CELL):
                continue
            nets[c] = dict(f1=m(c), sd=sd(c), d=m(c) - a,
                           ratio=abs(drift - a) / abs(m(c) - a))
        out[j["classifier"]] = dict(anchor=a, drift=drift, drift_sd=sd(DRIFT_CELL),
                                    ddrift=drift - a, nets=nets,
                                    k=r[0]["n_classes"])
    return out


def order_by(R, cell):
    """Classifiers ranked by drift/net ratio, least drift-dominated first."""
    names = [n for n in ORDER if n in R and cell in R[n]["nets"]]
    return sorted(names, key=lambda n: R[n]["nets"][cell]["ratio"])


def main():
    V = {}
    for label, d, axis, _ in VANTAGES:
        if os.path.isdir(d):
            R = load(d, axis)
            if R:
                V[label] = R
    if not V:
        print("no vantage results found")
        return 1

    L = ["# Both axes from one vantage, measured from two vantages", "",
         "Generated by `src/vantage_summary.py`. One training collection, one 20%",
         "anchor, one label space, with every network cell and the drift cell scored",
         "against it. Unlike the main table these are directly comparable to each other.",
         "The same test is then repeated from a second vantage, which turns out to",
         "matter.", ""]

    for label, d, axis, drift_label in VANTAGES:
        if label not in V:
            continue
        R = V[label]
        names = [n for n in ORDER if n in R]
        cells = sorted({c for n in names for c in R[n]["nets"]})
        k = R[names[0]]["k"]
        L += [f"## {label} vantage ({k} classes, 3 seeds)", "",
              "| Classifier | anchor | " +
              " | ".join(f"->{c.upper()}" for c in cells) +
              f" | {drift_label} | " +
              " | ".join(f"drift/->{c.upper()}" for c in cells) + " |",
              "|---|---|" + "---|" * (2 * len(cells) + 1)]
        first = cells[0]
        for n in sorted(names, key=lambda n: R[n]["nets"].get(first, {}).get("ratio", 0)):
            v = R[n]
            f1s = " | ".join(
                "n/a" if c not in v["nets"] else
                f"{v['nets'][c]['f1']:.4f} +/- {v['nets'][c]['sd']:.4f} ({v['nets'][c]['d']:+.3f})"
                for c in cells)
            ratios = " | ".join("n/a" if c not in v["nets"] else f"{v['nets'][c]['ratio']:.2f}"
                                for c in cells)
            L.append(f"| {n} | {v['anchor']:.4f} | {f1s} | "
                     f"{v['drift']:.4f} +/- {v['drift_sd']:.4f} ({v['ddrift']:+.3f}) | "
                     f"{ratios} |")
        L.append("")

    # ---- the finding, computed per (vantage, network cell)
    counts = []
    for label, _, _, _ in VANTAGES:
        if label not in V:
            continue
        R = V[label]
        for cell in sorted({c for n in R for c in R[n]["nets"]}):
            rs = [R[n]["nets"][cell]["ratio"] for n in R if cell in R[n]["nets"]]
            counts.append((f"{label} -> {cell.upper()}", sum(r < 1 for r in rs),
                           len(rs), min(rs), max(rs)))

    if counts:
        L += ["## What does not survive: which axis costs a classifier more", "",
              "A ratio below 1 means network mismatch costs the classifier more than six",
              "months of drift. Each vantage was run against two network cells, and the",
              "count depends on which one is read:", "",
              "| Vantage -> target | network-limited | ratios |", "|---|---|---|"]
        for name, n_lim, n_tot, lo, hi in counts:
            L.append(f"| {name} | **{n_lim} of {n_tot}** | {lo:.2f} to {hi:.2f} |")
        L.append("")

        nonzero = [c for c in counts if c[1] > 0]
        if len(nonzero) == 1:
            L += [f"Only **{nonzero[0][0]}** produces any network-limited classifier at all, "
                  f"{nonzero[0][1]} of {nonzero[0][2]}.",
                  "That is the single cell `netpairs/summary.md` finds hardest for every",
                  "classifier tested, so it is the most pessimistic of the four available. On",
                  "the other three, network mismatch is the cheaper axis for everything.", ""]
        elif not nonzero:
            L += ["No cell produces a network-limited classifier: drift is the more expensive",
                  "axis everywhere in this data.", ""]
        else:
            L += [f"{len(nonzero)} of the {len(counts)} cells produce at least one "
                  f"network-limited classifier, so the count is cell-dependent rather than",
                  "a property of the classifier.", ""]

        L += ["So group membership is set by which vantage the model was trained on and which",
              "country it is tested against, not by the classifier. An earlier draft of the",
              "Track A verdict claimed the AU result was the confound-free answer and that",
              "classifiers split cleanly into a network-limited group and a drift-limited",
              "one. That was wrong twice over: it removed the vantage confound from the",
              "comparison and then drew a conclusion from inside the pessimistic vantage,",
              "and within that vantage it read only the pessimistic of the two network",
              "cells that had been measured.",
              ""]

    # ---- what does survive: the ordering, checked across every cell
    orders = {}
    for label, _, _, _ in VANTAGES:
        if label not in V:
            continue
        for cell in sorted({c for n in V[label] for c in V[label][n]["nets"]}):
            orders[f"{label} -> {cell.upper()}"] = order_by(V[label], cell)

    if len(orders) >= 2:
        common = [n for n in ORDER if all(n in o for o in orders.values())]
        reduced = {k: [n for n in o if n in common] for k, o in orders.items()}

        L += ["## The ordering, and how much of it is invariant", "",
              "Ranking classifiers by how network-sensitive they are relative to their",
              "drift damage, least drift-dominated first:", "",
              "| Vantage -> target | order |", "|---|---|"]
        for name, o in orders.items():
            L.append(f"| {name} | {' < '.join(o)} |")
        L.append("")

        # The full ordering is invariant only if every cell induces the same one.
        # When it is not, the informative quantity is how much of it still is,
        # so the largest invariant subset is searched for rather than the result
        # being reported as a flat yes/no. Running Holmes on the UK vantage is
        # what made this necessary: four classifiers hold their order in every
        # cell and the fifth does not.
        stable = tuple(common)
        for k in range(len(common), 1, -1):
            cands = sorted(c for c in combinations(common, k)
                           if len({tuple(n for n in o if n in set(c))
                                   for o in reduced.values()}) == 1)
            if cands:
                stable = cands[0]
                break
        # Present it in ranked order, not declaration order. Every cell induces
        # the same order over this subset, so any one of them will do.
        stable = tuple(n for n in next(iter(reduced.values())) if n in set(stable))
        moved = [n for n in common if n not in stable]

        ratios = lambda key: [V[key.split(" -> ")[0]][n]["nets"]
                              [key.split(" -> ")[1].lower()]["ratio"] for n in common]
        keys = list(orders)
        rhos = [float(spearmanr(ratios(keys[i]), ratios(keys[j]))[0])
                for i in range(len(keys)) for j in range(i + 1, len(keys))]

        if not moved:
            L += [f"Identical across all {len(orders)} cells, over the {len(common)} "
                  f"classifiers run in every one of",
                  f"them. Pairwise Spearman {min(rhos):.3f} to {max(rhos):.3f}. The absolute "
                  f"ratios shift together by up to an",
                  "order of magnitude without reordering."]
        else:
            n_distinct = len({tuple(o) for o in reduced.values()})
            L += [f"**Not identical.** Over the {len(common)} classifiers run in every cell "
                  f"there are {n_distinct}",
                  f"distinct orders across the {len(orders)}, pairwise Spearman "
                  f"{min(rhos):.3f} to {max(rhos):.3f}.",
                  "",
                  f"What is invariant is the ordering of **{' < '.join(stable)}**, the same in",
                  f"all {len(orders)} cells, with the absolute ratios shifting together by up "
                  f"to an order of",
                  f"magnitude without reordering. {commas(moved)} "
                  f"{'moves' if len(moved) == 1 else 'move'} against "
                  f"{'that' if len(stable) else 'it'} ordering:"]
            for n in moved:
                L.append(f"{n} is " + commas(
                    f"{ordinal_pos(o.index(n) + 1)} in {k.replace(' -> ', '->')}"
                    for k, o in reduced.items()) + ".")

        # Which classifier heads and tails the ordering is computed, not asserted.
        heads = {tuple(n for n in o if n in stable)[0] for o in reduced.values()}
        tails = {tuple(n for n in o if n in stable)[-1] for o in reduced.values()}
        scope = "" if not moved else f" of the {len(stable)} that hold their order,"
        if len(heads) == 1 and len(tails) == 1:
            L += ["",
                  f"{next(iter(heads))} is the most network-sensitive relative to drift in",
                  f"every cell,{scope} and {next(iter(tails))} the least."]
        else:
            L += ["",
                  f"The classifier at the head of the ordering is not the same in every cell "
                  f"({', '.join(sorted(heads))}),",
                  f"and neither is the one at the tail ({', '.join(sorted(tails))})."]
        L += [""]

        L += ["## What this means for the hypothesis", "",
              "Read as *some classifiers are network-limited and others drift-limited*,",
              "the two-axis claim is **not supported**: which group a classifier lands in",
              "is a fact about the measurement setup.",
              ""]
        if not moved:
            L += ["Read as *classifiers differ consistently in how much network mismatch costs",
                  "them relative to drift*, it **is supported**, and that ordering is the most",
                  "stable quantity in this whole investigation. It is unchanged across every",
                  "vantage and target measured here, across the four country pairs of",
                  "`netpairs/summary.md`, and between this closed world and the thesis's open",
                  "world.",
                  ""]
        else:
            L += ["Read as *classifiers differ consistently in how much network mismatch costs",
                  "them relative to drift*, it **is supported for most of the set but not all",
                  f"of it**. {' < '.join(stable)} hold that order in every cell measured, and",
                  f"{commas(moved)} {'does' if len(moved) == 1 else 'do'} not, so it is a real",
                  "and stable property of those classifiers rather than of classifiers in",
                  "general. It is still the most stable quantity found anywhere in this",
                  "investigation: unchanged across the four country pairs of",
                  "`netpairs/summary.md` and between this closed world and the thesis's open",
                  "world.",
                  ""]
        L += ["It follows that a two-axis scatter plot is a misleading way to present",
              "this. A classifier's absolute position moves with the vantage and with the",
              "target country; only its position relative to the others is meaningful."]

    if "AU" in V and "UK" in V:
        missing = [n for n in ORDER if n in V["AU"] and n not in V["UK"]]
        if missing:
            L += ["",
                  f"**{', '.join(missing)} not run on the UK vantage.** It is the expensive",
                  "classifier and the others settle the question; its AU ratios are among the",
                  "lowest, so it would be expected to be drift-dominant on UK like the rest,",
                  "but that is an expectation and not a measurement."]

    out = os.path.join(RESULTS, "vantage", "summary.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
