#!/usr/bin/env python3
"""Write results/vantage/summary.md: both axes from one vantage, run twice.

The thesis's two headline axes do not share a training collection. Table 4.1
trains on AU and tests across networks; Table 4.3 trains on UK and tests across
time. Since AU-trained models degrade about 2.9x more in general (see
results/netpairs/summary.md), vantage and axis are entangled in the main result.

Each vantage axis removes that confound: one training collection, one 20%
in-distribution anchor, one label space, with both network and drift cells scored
against it. Running it from two vantages then asks whether the answer the
confound-free test gives is itself vantage-dependent. It is, which is why this
script reads both.

Usage: python vantage_summary.py
"""
import glob, json, os
import numpy as np
from scipy.stats import spearmanr

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")
VANTAGES = [("AU", os.path.join(RESULTS, "vantage"), "ca", "AU month 6"),
            ("UK", os.path.join(RESULTS, "vantage-uk"), "ca", "UK month 6")]
ORDER = ["k-FP", "DF", "Tik-Tok", "RF", "Holmes"]


def load(d, net_cell):
    out = {}
    for path in sorted(glob.glob(os.path.join(d, "*.json"))):
        j = json.load(open(path))
        r = j["rows"]
        m = lambda c: float(np.mean([x["f1_macro"] for x in r if x["cell"] == c]))
        sd = lambda c: float(np.std([x["f1_macro"] for x in r if x["cell"] == c]))
        a = m("in-dist")
        out[j["classifier"]] = dict(anchor=a, net=m(net_cell), drift=m("month6"),
                                    net_sd=sd(net_cell), drift_sd=sd("month6"),
                                    dnet=m(net_cell) - a, ddrift=m("month6") - a,
                                    ratio=abs(m("month6") - a) / abs(m(net_cell) - a),
                                    k=r[0]["n_classes"])
    return out


def main():
    V = {}
    for label, d, net_cell, _ in VANTAGES:
        if os.path.isdir(d):
            V[label] = load(d, net_cell)
    if not V:
        print("no vantage results found")
        return 1

    L = ["# Both axes from one vantage, measured from two vantages", "",
         "Generated by `src/vantage_summary.py`. One training collection, one 20%",
         "anchor, one label space, with both the network cell and the drift cell scored",
         "against it. Unlike the main table these are directly comparable to each other.",
         "The same test is then repeated from a second vantage, which turns out to",
         "matter.", ""]

    for label, d, net_cell, drift_label in VANTAGES:
        if label not in V:
            continue
        R = V[label]
        names = [n for n in ORDER if n in R]
        k = R[names[0]]["k"]
        L += [f"## {label} vantage ({k} classes, 3 seeds)", "",
              f"| Classifier | anchor | ->{net_cell.upper()} | {drift_label} | net | drift | drift/net |",
              "|---|---|---|---|---|---|---|"]
        for n in sorted(names, key=lambda n: R[n]["ratio"]):
            v = R[n]
            L.append(f"| {n} | {v['anchor']:.4f} | {v['net']:.4f} +/- {v['net_sd']:.4f} | "
                     f"{v['drift']:.4f} +/- {v['drift_sd']:.4f} | {v['dnet']:+.3f} | "
                     f"{v['ddrift']:+.3f} | {v['ratio']:.2f} |")
        L.append("")

    # ---- the finding
    if len(V) >= 2:
        au, uk = V["AU"], V["UK"]
        n_au = sum(v["ratio"] < 1 for v in au.values())
        n_uk = sum(v["ratio"] < 1 for v in uk.values())
        common = [n for n in ORDER if n in au and n in uk]
        rho, _ = spearmanr([au[n]["ratio"] for n in common],
                           [uk[n]["ratio"] for n in common])
        order_au = " < ".join(sorted(common, key=lambda n: au[n]["ratio"]))
        order_uk = " < ".join(sorted(common, key=lambda n: uk[n]["ratio"]))

        L += ["## What does not survive: which axis costs a classifier more", "",
              f"A ratio below 1 means network mismatch costs the classifier more than six",
              f"months of drift. From the AU vantage **{n_au} of {len(au)}** classifiers are",
              f"network-limited. From the UK vantage **{n_uk} of {len(uk)}** are, with every",
              f"ratio between {min(v['ratio'] for v in uk.values()):.1f} and "
              f"{max(v['ratio'] for v in uk.values()):.1f}.",
              "",
              "So group membership is set by the training vantage, not by the classifier.",
              "An earlier draft of the Track A verdict claimed the AU result was the",
              "confound-free answer and that classifiers split cleanly into a",
              "network-limited group and a drift-limited one. That was wrong: it removed",
              "the vantage confound from the comparison and then drew a conclusion from",
              "inside the pessimistic vantage, which `netpairs/summary.md` had already",
              "identified as the worst of the available choices for network mismatch.",
              "",
              "## What does survive: the ordering", "",
              "Ranking classifiers by how network-sensitive they are relative to their",
              "drift damage, least drift-dominated first:", "",
              "| Vantage | order |", "|---|---|",
              f"| AU | {order_au} |", f"| UK | {order_uk} |", "",
              f"Identical, Spearman {rho:.3f} over the {len(common)} classifiers run on",
              "both. The absolute ratios shift together by roughly a factor of three",
              "without reordering. RF is the most network-sensitive relative to drift from",
              "either vantage, and DF the least.",
              "",
              "## What this means for the hypothesis", "",
              "Read as *some classifiers are network-limited and others drift-limited*,",
              "the two-axis claim is **not supported**: which group a classifier lands in",
              "is a fact about the measurement setup.",
              "",
              "Read as *classifiers differ consistently in how much network mismatch costs",
              "them relative to drift*, it **is supported**, and that ordering is the most",
              "stable quantity in this whole investigation. It is unchanged across the two",
              "vantages here, across the four country pairs of `netpairs/summary.md`, and",
              "between this closed world and the thesis's open world.",
              "",
              "It follows that a two-axis scatter plot is a misleading way to present",
              "this. A classifier's absolute position moves with the vantage; only its",
              "position relative to the others is meaningful."]

        missing = [n for n in ORDER if n in au and n not in uk]
        if missing:
            L += ["",
                  f"**{', '.join(missing)} not run on the UK vantage.** It is the expensive",
                  "classifier and the others settle the question; its AU ratio is among the",
                  "lowest, so it would be expected to be drift-dominant on UK like the rest,",
                  "but that is an expectation and not a measurement."]

    out = os.path.join(RESULTS, "vantage", "summary.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
